### ISSUE TITLE
install of afedR failed 

### ISSUE THREAD

**Issue by MargareeMan** [msperlin/afedR#1]
This is the output from my attempt to download the afedR repo:

> library(devtools)
Loading required package: usethis
> devtools::install_github('msperlin/afedR')
Downloading GitHub repo msperlin/afedR@master
msperlin-afedR-91c4aab/inst/extdata/data/SQLite_db.SQLITE: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Failed to install 'afedR' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\whale\AppData\Local\Temp\Rtmp2FzTPF\file10a45d6e5185.tar.gz" -C "C:/Users/whale/AppData/Local/Temp/Rtmp2FzTPF/remotes10a449b412c7"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Users\whale\AppData\Local\Temp\Rtmp2FzTPF\file10a45d6e5185.tar.gz"' had status 1

--------------------------------------  system info

R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.2.1 usethis_1.5.1

**Comment by msperlin** [comment]
Hi MargareeMan,

Its working fine here:

Installing package into ‘/home/msperlin/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘afedR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (afedR)

There are some warning messages, but you can ignore them. 

Can you try it again and let me know how it goes?

**Comment by MargareeMan** [comment]
Hi,

 

I have rerun the installation.  This time on my DSL internet access.  It worked.  Last night, when the install failed, I was connected via my satellite link (we are located in rural Cape Breton, Nova Scotia, CA).  I do no know if this made the difference.  But, thanks for the response.

 

Appreciate you assistance,

 

George

**Comment by msperlin** [comment]
Great.
