### ISSUE TITLE
devtools::install_github('msperlin/adfeR')  não está mais disponível?

### ISSUE THREAD

**Issue by andreltr** [msperlin/afedR#2]
Olá,

O pacote acima não está mais disponível?  Eu não consegui baixa-lo no link informado, senão vejamos,

> devtools::install_github('msperlin/adfeR') 
Downloading GitHub repo msperlin/adfeR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/msperlin/adfeR/tarball/HEAD' failed
> devtools::install_github('msperlin/adfeR')
Downloading GitHub repo msperlin/adfeR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/msperlin/adfeR/tarball/HEAD' failed
> 

Desde já agradeço qualquer explicação sobre como resolver essa situação.

Atenciosamente,

--
André Luiz Tietböhl Ramos, Dr.

**Comment by msperlin** [comment]
Oi André, 

Testei aqui e funcionou. O Github tem uma cota diária de downloads anonimos. Talvez tenha passado essa cota? Tenta de novo e me diga com foi.
